static_sites:
  - name: check-master
    buildCommand: npm install && npm run build
    publishDir: dist/demo/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html